spring:
  profiles:
    active: local
  application:
    name: gateway-service
  config:
    import:
      - "configserver:"
      - optional:file:.env[.properties]
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18080/eureka/

springdoc:
  swagger-ui:
    urls:
      - name: hub-service
        url: /api/hubs/v3/api-docs
      - name: user-service
        url: /api/user/v3/api-docs
      - name: order-service
        url: /api/orders/v3/api-docs
      - name: product-service
        url: /api/products/v3/api-docs
      - name: notification-service
        url: /api/slacks/v3/api-docs
      - name: company-service
        url: /api/companies/v3/api-docs
      - name: delivery-service
        url: /api/deliveries/v3/api-docs

jwt:
  secret-key: ${JWT_SECRET_KEY}