spring:
  profiles:
    active: local
  application:
    name: gateway-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18080/eureka/

springdoc:
  swagger-ui:
    urls:
      - name: hub-service
        url: /api/hubs/v3/api-docs
      - name: user-service
        url: /api/user/v3/api-docs
      - name: order-service
        url: /api/orders/v3/api-docs
      - name: product-service
        url: api/products/v3/api-docs
      - name: notification-service
        url: api/notification/v3/api-docs
