spring:
  profiles:
    active: docker
  application:
    name: hub-service
  config:
    import:
      - "configserver:"
      - optional:file:.env[.properties]
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    service-url:
      defaultZone: http://eureka:18080/eureka/


naver:
  map:
    client-id : ${NAVER_CLIENT_ID}
    secret-key : ${NAVER_SECRET_KEY}

